FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /source

ARG prj=CakeStore.Presentation.csproj
ARG path=Core/Presentation/CakeStore.Presentation

COPY NuGet.Config /
COPY ${path}/${prj} ./${path}/
RUN dotnet restore ${path}/${prj}
COPY . .
RUN dotnet publish ${path}/${prj} -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CakeStore.Presentation.dll"]